## To include in the paper.

#####
## NFL
##
## Carrying out preliminary diagnostics for:
##  * Classic linear regression (via regular residuals-vs-fitted and QQ-plots)
##  * Ordinal regression (via surrogate residual approach, creating analogs of residuals-vs-fitted and QQ-plots)
## when using all the complementary features under consideration as predictors,
## along with various combinations of game context variables (e.g., score differential, time left in the game)
## in terms of interaction terms.
#####

### Tried ADDING INTERACTION TERMS as well. High significance, but NO REAL IMPROVEMENT TO GOF tests

library(tidyverse)
library(car)
library(fuzzyjoin)
library(sure)
library(ordinal)
library(ggplot2)
library(ggfortify)
library(ggplotify)
library(grid)


# We will be combining the yards for offense and special teams returns.
yds.combine <- TRUE




for (year in 2009:2017){
  
  print(year)
  
  
  # load(paste0("pbp_by_drive_",year,".Robj"))
  # print(summary(pbp_by_drive$drive_duration_seconds))
  
  # Checking all distinct drive outcomes
  # full_pbp_by_drive  <- read.csv("NFL_2009_2017_Drive_by_Drive_Data_Cleaned.csv")
  # table(full_pbp_by_drive$drive_Outcome)
  
  # Defensive Touchdown         End of Half              Fumble        Interception     Made Field Goal   Missed Field Goal 
  # 456                3675                2626                3588                7331                1412 
  # Offensive Touchdown                Punt              Safety   Turnover on Downs 
  # 10456               21645                 101                1838 
  
  pbp_by_drive <- read.csv("NFL_2009_2017_Drive_by_Drive_Data_Cleaned.csv") %>%
    filter(Season == year)
  
  ## Just make onside kick stuff a Fumble, for simplicity
  pbp_by_drive$drive_Outcome[pbp_by_drive$drive_Outcome == "Onside Kick Recovered / Fumble"] <- "Fumble"
  
  table(pbp_by_drive$drive_Outcome)
  
  ## Getting an ID variable
  pbp_by_drive$game_id_half <- paste0(pbp_by_drive$GameID, "-", pbp_by_drive$drive_half_start)
  
  
  ## Non-scoring FORCED TOs, such as picks, fumbles, on-side kick recovery
  pbp_by_drive$takeaways.nonscor <- pbp_by_drive$drive_Outcome %in% c("Fumble", # "Fumble Recovery (Opponent)",
                                                                      "Interception" # "Interception Return",
                                                                      # "Kickoff Team Fumble Recovery",
                                                                      # "Punt Team Fumble Lost",
                                                                      #  "Blocked Punt Team Fumble Lost",
                                                                      #  "On-Side Kick Lost"
  )
  
  ## Any TOs, including FG misses/blocks, turnover on downs
  pbp_by_drive$turnovers.nonscor <- (pbp_by_drive$takeaways.nonscor | 
                                       pbp_by_drive$drive_Outcome %in% c(# "Blocked Field Goal",
                                         # "Field Goal Missed",
                                         "Missed Field Goal", # "Missed Field Goal Return",
                                         "Turnover on Downs" #, "Downs Turnover"
                                       )
  )
  
  pbp_by_drive$defensive.score <- pbp_by_drive$drive_Outcome %in% c("Defensive Touchdown")
  
  
  ## Punts or safeties (both result in turning the ball over via a 'punting motion', although the latter also has -2 pts)
  pbp_by_drive$punt.safety <- pbp_by_drive$drive_Outcome %in% c("Punt", "Safety")
  
  ## Number of positive runs
  # pbp_by_drive$n.positive.runs <- pbp_by_drive$n.rush - pbp_by_drive$n.stuffed.runs
  
  ## Special team return variables:
  pbp_by_drive$yds_ST_return_net <- pbp_by_drive$ST.return.yards.net
  
  
  ####
  ## Combining the yards for offense and special teams.
  ####
  if (yds.combine == TRUE){
    
    # pbp_by_drive$off.yards_gained <- pbp_by_drive$off.yards_gained + pbp_by_drive$yds_ST_return
    pbp_by_drive$off.yards_gained <- pbp_by_drive$off.ST.yards.gained
  }
  
  #####
  ## Creating the indicator variable for "complementary drives", as in - anything but
  #     1) Kickoffs at the start of halves, 
  #     2) Drives directly after a defensive touchdown.
  #####
  
  pbp_by_drive$complem.ind <- ifelse(lag(pbp_by_drive$game_id_half) == pbp_by_drive$game_id_half,
                                     ifelse(lag(pbp_by_drive$pos_team) != pbp_by_drive$pos_team,
                                            1,
                                            0),
                                     1)
  pbp_by_drive$complem.ind[1] <- 0   # Cleaning up the "NA" generated by the first lag
  
  pbp_by_drive$n.negative.plays.with.penalties <- pbp_by_drive$n.negative.plays
  
  
  #####
  ## CHECKING SCORING OUTCOMES
  ## (ALREADY DONE IN "RESubmission_NFL_0_Cleaning_up_Drive_Points.R")
  #####
  
  pbp_by_drive$score_pts_by_text <- pbp_by_drive$pts.scored
  
  # There was always an issue with keeping track of extra point for defensive TD, 
  # so gotta switch from "-6" to "-7"
  
  pbp_by_drive$score_pts_by_text[pbp_by_drive$score_pts_by_text == -6] <- -7
  
  
  #  View(pbp_by_drive %>% filter(pts.scored == -6, drive_Outcome == "Fumble"))
  
  
  
  
  ## All the complementary statistics under consideration
  relev.var.names <- c("n.completions", "n.incompletions", "n.stuffed.runs", "n.positive.runs", "n.negative.plays.with.penalties",
                       "off.yards_gained",
                       "score_pts_by_text",
                       "yds_ST_return_net", 
                       # "yds_ST_return",
                       "n.sacks", "n.fumbles",
                       "first.downs.gained", "third.downs.converted",
                       "turnovers.nonscor",
                       "punt.safety"
  )
  
  # Initializing a lagged variable set
  pbp_by_drive_lag_vars <- data.frame(game_id_half = pbp_by_drive$game_id_half,
                                      pos_team = pbp_by_drive$pos_team,
                                      # pbp_by_drive[, 8:ncol(pbp_by_drive)]
                                      pbp_by_drive[, relev.var.names]
  )
  
  
  # For numerical variables, creating their lagged values, 
  for (c.ind in 3:ncol(pbp_by_drive_lag_vars)){
    pbp_by_drive_lag_vars[, c.ind] <- lag(pbp_by_drive_lag_vars[, c.ind])
    pbp_by_drive_lag_vars[1, c.ind] <- pbp_by_drive_lag_vars[2, c.ind] # For the initial NA value, which will get wiped out by complem.ind=0 anyway
  }
  
  # Making the variable names for lagged values explicit (adding "lagged" to them)
  colnames(pbp_by_drive_lag_vars)[3:ncol(pbp_by_drive_lag_vars)] <- paste0("lagged_", colnames(pbp_by_drive_lag_vars)[3:ncol(pbp_by_drive_lag_vars)])
  
  # Merging the lagged values into original data set
  pbp_by_drive <- data.frame(pbp_by_drive, pbp_by_drive_lag_vars[,-1])
  
  
  
  ## If we combine yards, then DROP the "yds_ST_return"
  # if (yds.combine) relev.var.names <- relev.var.names[relev.var.names != "yds_ST_return"]
  
  
  #######
  ## Complementary statistics to be included in the model for testing:
  #######
  
  relev.var.names.lagged <- paste0("lagged_", relev.var.names)
  
  ## ADDING THE START_POS ONES to LAGGED VARIABLES
  ## 

  pbp_by_drive$lagged_start_pos_post_turnover <- ifelse(pbp_by_drive$lagged_turnovers.nonscor, 
                                                        100-pbp_by_drive$off.ST.start.pos,
                                                        100-mean(pbp_by_drive$off.ST.start.pos[pbp_by_drive$lagged_turnovers.nonscor]))
  

  
  
  ## Defining the categorical ordinal scoring outcome variable
  
  pbp_by_drive$categ.score <- ifelse(pbp_by_drive$score_pts_by_text %in% c(6,7,8),
                                     "Offensive TD",
                                     ifelse(pbp_by_drive$score_pts_by_text == 3,
                                            "Field Goal",
                                            ifelse(pbp_by_drive$score_pts_by_text == -2,
                                                   "Safety",
                                                   ifelse(pbp_by_drive$score_pts_by_text == 2,
                                                          NA,
                                                          ifelse(pbp_by_drive$score_pts_by_text %in% c(-6,-7,-8),
                                                                 "Defensive TD",
                                                                 "No Score")))))
  
  pbp_by_drive$categ.score <- factor(pbp_by_drive$categ.score,
                                     ordered=T,
                                     levels = c("Defensive TD", "Safety", "No Score", "Field Goal", "Offensive TD"))
  
  
  
  
  ## Time left in half
  # "drive_TimeSecs_start" - doesn't look good, a bunch of negative values, etc..
  # Just using the "drive_time_start", which looks way more reliable
  
  pbp_by_drive$drive_time_left_in_half <-  as.numeric(substr(pbp_by_drive$drive_time_start, 1, 2)) +
    as.numeric(substr(pbp_by_drive$drive_time_start, 4, 5))/60 +
    ifelse(pbp_by_drive$drive_qtr_start %in% c(1,3),
           15,
           0)
  
  ## Convert the half from having 3 categories ("1st", "2nd", "OT") 
  ##  into having just 2: ("1st", "2nd/OT")
  ## which makes sense from the end-goal perspective: 
  ##  we draw a difference between the mere end of 1st half, and 
  ##  the actual end of games (which is end of 2nd half, or OT) where the score is infinitely more important
  
  
  pbp_by_drive$drive_half_start <- ifelse(pbp_by_drive$drive_half_start %in% c("2nd", "OT"),
                                          "2nd/OT",
                                          pbp_by_drive$drive_half_start)
  
  
  # pbp_by_drive$drive_time_left_in_half <- pbp_by_drive$drive_time_minutes_start + 
  #   pbp_by_drive$drive_time_seconds_start/60 +
  #   ifelse(pbp_by_drive$drive_qtr_start %in% c(1,3),
  #          15,
  #          0)
  
  
  
  
  ## Game ID & Score differential - need to just rename the variables
  pbp_by_drive <- pbp_by_drive %>% 
    rename(game_id = GameID,
           score_diff_start = drive_ScoreDiff_start)
  
  
  ######
  ## LINEAR REGRESSION
  ######
  
  #### UNCOMMENT if you need the LINEAR REGRESSION residuals
  
  our.df <- pbp_by_drive[, c("score_pts_by_text", "categ.score",
                              "pos_team", "def_pos_team", "pos.homefield", "complem.ind",
                              relev.var.names.lagged,
                              "score_diff_start",
                              "drive_time_left_in_half",
                              "drive_half_start",
                             "lagged_start_pos_post_turnover")] 
  
  if (stand == FALSE) {
    our.df <- our.df %>%
      mutate_if(is.numeric, scale) 
    our.df$complem.ind <- as.numeric(our.df$complem.ind)
    our.df$lagged_turnovers.nonscor <- as.numeric(our.df$lagged_turnovers.nonscor)
  }
  
  our.df$complem.ind <- as.numeric(our.df$complem.ind)
  
  our.df$lagged_turnovers.nonscor <- as.numeric(our.df$lagged_turnovers.nonscor)
  
  
  lm.obj <- lm(# score_pts_by_text ~ . + score_diff_start*drive_time_left_in_half*drive_half_start,
    formula(paste0("score_pts_by_text ~", paste0(c("pos_team", "def_pos_team", "pos.homefield", "complem.ind"
                                                   , paste0(c(relev.var.names.lagged, 
                                                            "lagged_turnovers.nonscor:lagged_start_pos_post_turnover"),
                                                            ":complem.ind", sep="")
                                                   , "score_diff_start", "drive_time_left_in_half", "drive_half_start"
                                                   , "score_diff_start:drive_time_left_in_half", "score_diff_start:drive_half_start", "drive_time_left_in_half:drive_half_start"
                                                   
                                                   # , "off.ST.start.pos"   # IF ONE WANTS TO CHECK THE STARTING POSITION EFFECT
                                                   #    , "score_diff_start*drive_time_left_in_half*drive_half_start"
    ),
    collapse = " + "), collapse =" ")),
    data = our.df
    )
  summary(lm.obj)
  
  print(tail(summary(lm.obj)$coefficients, 20))
  
  par(mfrow = c(1, 2), oma = c(0, 0, 3, 0))
  plot(lm.obj, which=c(1,2), main="")
  #plot(lm.obj, which=2, main="" )
  mtext(paste0("Linear regression fit diagnostics, \nNFL, Year ", year ), side = 3, line = -3, outer = TRUE, cex = 1.5)
  
  par(mfrow=c(1,1))
  
  
  # Checking collinearity
  # print(vif(lm.obj, type="predictor"))
  
  
  ######
  ## ORDINAL REGRESSION
  ######
  
  
  clm.obj <- clm(formula(paste0("categ.score ~", paste0(c("pos_team", "def_pos_team", "pos.homefield", "complem.ind", 
                                                          paste0(c(
                                                            "lagged_turnovers.nonscor"
                                                                   ,"lagged_turnovers.nonscor:lagged_start_pos_post_turnover"
                                                          ),
                                                          ":complem.ind", sep="")
                                                          , "score_diff_start", "drive_time_left_in_half", "drive_half_start"
                                                          , "score_diff_start:drive_time_left_in_half", "score_diff_start:drive_half_start", "drive_time_left_in_half:drive_half_start"
                                                          # , "off.ST.start.pos"   # IF ONE WANTS TO CHECK THE STARTING POSITION EFFECT
                                                          #    , "score_diff_start*drive_time_left_in_half*drive_half_start"
  ),
  collapse = " + "), collapse =" ")),
  data=na.omit(our.df))
  
  
  # clm.obj$coefficients
  # clm.full.obj$coefficients
  
  print(tail(summary(clm.obj)$coefficients, 20))
  # print(tail(summary(clm.obj)$coefficients, 20))  # IF ONE WANTS TO CHECK THE STARTING POSITION EFFECT
  
  ## DIAGNOSTICS:
  ## width: 650;  Height 400
  
  set.seed(100) # for reproducibility
  p1 <- autoplot.clm(clm.obj, what = c("fitted")) + ggtitle(paste0("Surrogate Residuals-vs-Fitted")) #
  p2 <- autoplot.clm(clm.obj, what = c("qq")) + ggtitle(paste0("Surrogate Quantile-Quantile")) #
  print(grid.arrange(p1, p2, ncol = 2,
                     top = textGrob(paste0("Ordinal regression fit diagnostics, \nNFL, Year ", year ), gp = gpar(fontsize = 16))))
  
  
}


# dev.off()

######
## P-values => 
##    For the TRIPLE-INTERACTION:
##      score_diff_start:drive_time_left_in_half:drive_half_start2nd/OT  =>  INsignificant in 8/9 cases (only one significant, barely)

## REMOVING TRIPLE,
##    For the DOUBLE-INTERACTIONS:
##      score_diff_start:drive_time_left_in_half => signif 5/9
##      score_diff_start:drive_half_start2nd/OT => signif 5/9
##      drive_time_left_in_half:drive_half_start2nd/OT => signif 6/9


###
# Year=2009
# 
# score_diff_start:drive_time_left_in_half        0.087246064 0.03220556  2.70903726 0.006747876
# score_diff_start:drive_half_start2nd/OT        -0.202267073 0.07015169 -2.88328156 0.003935555
# drive_time_left_in_half:drive_half_start2nd/OT  0.152936070 0.05680952  2.69208545 0.007100675


# Year=2010
#
# score_diff_start:drive_time_left_in_half        0.06073516 0.03194629  1.9011648 0.057280432
# score_diff_start:drive_half_start2nd/OT        -0.19435471 0.06854274 -2.8355256 0.004575035
# drive_time_left_in_half:drive_half_start2nd/OT  0.13287939 0.05579173  2.3817038 0.017232754


# Year=2011
#
# score_diff_start:drive_time_left_in_half        0.05580046 0.03218303  1.7338472 0.0829451951
# score_diff_start:drive_half_start2nd/OT        -0.08628265 0.07077306 -1.2191453 0.2227890449
# drive_time_left_in_half:drive_half_start2nd/OT  0.19280498 0.05616192  3.4330200 0.0005968981


# Year=2012
#
# score_diff_start:drive_time_left_in_half        0.03082442 0.03106809  0.9921568 0.32112102
# score_diff_start:drive_half_start2nd/OT        -0.12227181 0.06888707 -1.7749601 0.07590447
# drive_time_left_in_half:drive_half_start2nd/OT  0.06642257 0.05486010  1.2107628 0.22598632


# Year=2013
#
# score_diff_start:drive_time_left_in_half        0.07658873 0.03086658  2.481283 0.0130910353
# score_diff_start:drive_half_start2nd/OT        -0.17651180 0.06819078 -2.588500 0.0096395055
# drive_time_left_in_half:drive_half_start2nd/OT  0.16008071 0.05473940  2.924415 0.0034510485


# Year=2014
#
# score_diff_start:drive_time_left_in_half        0.08254244 0.03164698  2.60822519 0.0091013059
# score_diff_start:drive_half_start2nd/OT        -0.22933243 0.06911919 -3.31792696 0.0009068819
# drive_time_left_in_half:drive_half_start2nd/OT  0.17911527 0.05528567  3.23981366 0.0011960783


# Year=2015
#
# score_diff_start:drive_time_left_in_half        0.07631218 0.03147805  2.4242983 0.015337999
# score_diff_start:drive_half_start2nd/OT        -0.18688649 0.06829600 -2.7364192 0.006211185
# drive_time_left_in_half:drive_half_start2nd/OT  0.10308216 0.05439753  1.8949786 0.058095239

# Year=2016
#
# score_diff_start:drive_time_left_in_half        0.10688776 0.03189288  3.3514611 0.0008038633
# score_diff_start:drive_half_start2nd/OT        -0.12700269 0.06533539 -1.9438576 0.0519126277
# drive_time_left_in_half:drive_half_start2nd/OT  0.08784414 0.05514852  1.5928648 0.1111905267


# Year: 2017
#
# score_diff_start:drive_time_left_in_half        0.06048811 0.03163096  1.912307 0.0558368162
# score_diff_start:drive_half_start2nd/OT        -0.08111620 0.07202627 -1.126203 0.2600795837
# drive_time_left_in_half:drive_half_start2nd/OT  0.19592168 0.05481811  3.574032 0.0003515264