## To be included in the paper

#######
## NFL
##
## Calculating the full data fit (non-bootstrapped; just a single fit)
##  for the reduced set of selected features (the turnovers and post_turnover_start_pos)
##
## Resulting fitted objects are saved as follows:
## save(projected.points.intercept, file= paste0("RESUBMISSION_NFL_W_START_POS_ORDNET_projected.points.intercept.RData"))
## save(ordnet.fits, file=paste0("RESUBMISSION_NFL_W_START_POS_ORDNET_ordnet.fits.RData"))
##
## They are used later in Stages 5,6,7 for
## plotting effects (Parts 5 & 6) and the residual diagnostics (Part 7)
#######

library(tidyverse)
library(car)
library(fuzzyjoin)
library(sure)
library(ordinal)
library(ggplot2)
library(ggfortify)

## Seed for reproducibility of CV
set.seed(1)

library(ordinalNet)
library(tidyverse)

# Loading the enhanced ordinalNet code.
source("Submission_0_ordinalNet_package_source_code_enhanced.R")

# We will only focus on the complementary statistics that were consistently picked
# (yards gained and non-scoring takeaways)
all.variables <- FALSE

# We will be combining the yards for offense and special teams returns.
yds.combine <- TRUE




## alpha trade-off value
alpha.val <- 0.99

projected.points <- NULL
projected.points.intercept <- NULL
ordnet.fits <- NULL



for (year in 2009:2017){
  
  print("Year:")
  print(year)
  
  
  pbp_by_drive <- read.csv("NFL_2009_2017_Drive_by_Drive_Data_Cleaned.csv") %>%
    filter(Season == year)
  
  
  ## Just make onside kick stuff a Fumble, for simplicity
  pbp_by_drive$drive_Outcome[pbp_by_drive$drive_Outcome == "Onside Kick Recovered / Fumble"] <- "Fumble"
  
  
  table(pbp_by_drive$drive_Outcome)
  
  
  ## Getting an ID variable
  pbp_by_drive$game_id_half <- paste0(pbp_by_drive$GameID, "-", pbp_by_drive$drive_half_start)
  
  ## Non-scoring FORCED TOs, such as picks, fumbles, on-side kick recovery
  pbp_by_drive$takeaways.nonscor <- pbp_by_drive$drive_Outcome %in% c("Fumble", # "Fumble Recovery (Opponent)",
                                                                      "Interception" # "Interception Return",
                                                                      # "Kickoff Team Fumble Recovery",
                                                                      # "Punt Team Fumble Lost",
                                                                      #  "Blocked Punt Team Fumble Lost",
                                                                      #  "On-Side Kick Lost"
  )
  
  ## Any TOs, including FG misses/blocks, turnover on downs
  pbp_by_drive$turnovers.nonscor <- (pbp_by_drive$takeaways.nonscor |
                                       pbp_by_drive$drive_Outcome %in% c(# "Blocked Field Goal",
                                         # "Field Goal Missed",
                                         "Missed Field Goal", # "Missed Field Goal Return",
                                         "Turnover on Downs" #, "Downs Turnover"
                                       )
  )
  
  pbp_by_drive$defensive.score <- pbp_by_drive$drive_Outcome %in% c("Defensive Touchdown")
  
  
  ## Punts or safeties (both result in turning the ball over via a 'punting motion', although the latter also has -2 pts)
  pbp_by_drive$punt.safety <- pbp_by_drive$drive_Outcome %in% c("Punt", "Safety")
  
  ## Number of positive runs
  # pbp_by_drive$n.positive.runs <- pbp_by_drive$n.rush - pbp_by_drive$n.stuffed.runs
  
  ## Special team return variables:
  pbp_by_drive$yds_ST_return_net <- pbp_by_drive$ST.return.yards.net
  
  
  ####
  ## Combining the yards for offense and special teams.
  ####
  if (yds.combine == TRUE){
    
    # pbp_by_drive$off.yards_gained <- pbp_by_drive$off.yards_gained + pbp_by_drive$yds_ST_return
    pbp_by_drive$off.yards_gained <- pbp_by_drive$off.ST.yards.gained
  }
  
  
  #####
  ## Creating the indicator variable for "complementary drives", as in - anything but
  #     1) Kickoffs at the start of halves,
  #     2) Drives directly after a defensive touchdown.
  #####
  
  pbp_by_drive$complem.ind <- ifelse(lag(pbp_by_drive$game_id_half) == pbp_by_drive$game_id_half,
                                     ifelse(lag(pbp_by_drive$pos_team) != pbp_by_drive$pos_team,
                                            1,
                                            0),
                                     1)
  pbp_by_drive$complem.ind[1] <- 0   # Cleaning up the "NA" generated by the first lag
  
  pbp_by_drive$n.negative.plays.with.penalties <- pbp_by_drive$n.negative.plays
  
  
  pbp_by_drive$score_pts_by_text <- pbp_by_drive$pts.scored
  
  # There was always an issue with keeping track of extra point for defensive TD,
  # so gotta switch from "-6" to "-7"
  
  pbp_by_drive$score_pts_by_text[pbp_by_drive$score_pts_by_text == -6] <- -7
  
  
  
  ## All the complementary statistics under consideration
  relev.var.names <- c("n.completions", "n.incompletions", "n.stuffed.runs", "n.positive.runs", "n.negative.plays.with.penalties",
                       "off.yards_gained",
                       "score_pts_by_text",
                       "yds_ST_return_net",
                       # "yds_ST_return",
                       "n.sacks", "n.fumbles",
                       "first.downs.gained", "third.downs.converted",
                       "takeaways.nonscor", "turnovers.nonscor",
                       "punt.safety"
  )
  
  
  # Initializing a lagged variable set
  pbp_by_drive_lag_vars <- data.frame(game_id_half = pbp_by_drive$game_id_half,
                                      pos_team = pbp_by_drive$pos_team,
                                      # pbp_by_drive[, 8:ncol(pbp_by_drive)]
                                      pbp_by_drive[, relev.var.names]
  )
  
  
  # For numerical variables, creating their lagged values,
  for (c.ind in 3:ncol(pbp_by_drive_lag_vars)){
    pbp_by_drive_lag_vars[, c.ind] <- lag(pbp_by_drive_lag_vars[, c.ind])
    # pbp_by_drive_lag_vars[1, c.ind] <- 0 # For the initial NA value
    pbp_by_drive_lag_vars[1, c.ind] <- pbp_by_drive_lag_vars[2, c.ind] # For the initial NA value
  }
  
  # Making the variable names for lagged values explicit (adding "lagged" to them)
  colnames(pbp_by_drive_lag_vars)[3:ncol(pbp_by_drive_lag_vars)] <- paste0("lagged_", colnames(pbp_by_drive_lag_vars)[3:ncol(pbp_by_drive_lag_vars)])
  
  # Merging the lagged values into original data set
  pbp_by_drive <- data.frame(pbp_by_drive, pbp_by_drive_lag_vars[,-1])
  
  
  
  ## If we combine yards, then DROP the "yds_ST_return"
  #  if (yds.combine) relev.var.names <- relev.var.names[relev.var.names != "yds_ST_return"]
  
  pbp_by_drive$lagged_start_pos_post_takeaway <- ifelse(pbp_by_drive$lagged_takeaways.nonscor == 1,
                                                        100-pbp_by_drive$off.ST.start.pos,
                                                        100-mean(pbp_by_drive$off.ST.start.pos[pbp_by_drive$lagged_takeaways.nonscor == 1]))
  
  pbp_by_drive$lagged_start_pos_post_turnover <- ifelse(pbp_by_drive$lagged_turnovers.nonscor == 1,
                                                        100-pbp_by_drive$off.ST.start.pos,
                                                        100-mean(pbp_by_drive$off.ST.start.pos[pbp_by_drive$lagged_turnovers.nonscor == 1]))
  
  
  
  #######
  ## Complementary statistics to be included in the model for testing:
  #######
  
  # relev.var.names.lagged <- paste0("lagged_", relev.var.names)
  
  if (all.variables){
    relev.var.names.lagged <- paste0("lagged_", relev.var.names)
  } else {
    # relev.var.names <- c("off.yards_gained",
    #                      "takeaways.nonscor")
    relev.var.names.lagged <- c("lagged_turnovers.nonscor",
                                "lagged_start_pos_post_turnover")
  }
  
  ## Defining the categorical ordinal scoring outcome variable
  
  pbp_by_drive$categ.score <- ifelse(pbp_by_drive$score_pts_by_text %in% c(6,7,8),
                                     "Offensive TD",
                                     ifelse(pbp_by_drive$score_pts_by_text == 3,
                                            "Field Goal",
                                            ifelse(pbp_by_drive$score_pts_by_text == -2,
                                                   "Safety",
                                                   ifelse(pbp_by_drive$score_pts_by_text == 2,
                                                          NA,
                                                          ifelse(pbp_by_drive$score_pts_by_text %in% c(-6,-7,-8),
                                                                 "Defensive TD",
                                                                 "No Score")))))
  
  
  pbp_by_drive$categ.score <- factor(pbp_by_drive$categ.score,
                                     ordered=T,
                                     levels = c("Defensive TD", "Safety", "No Score", "Field Goal", "Offensive TD"))
  
  
  
  
  ###########
  ###########
  ### Calculating PROJECTED POINTS for EACH TEAM
  ###########
  ###########
  
  ## Time left in half
  # "drive_TimeSecs_start" - doesn't look good, a bunch of negative values, etc..
  # Just using the "drive_time_start", which looks way more reliable
  
  pbp_by_drive$drive_time_left_in_half <-  as.numeric(substr(pbp_by_drive$drive_time_start, 1, 2)) +
    as.numeric(substr(pbp_by_drive$drive_time_start, 4, 5))/60 +
    ifelse(pbp_by_drive$drive_qtr_start %in% c(1,3),
           15,
           0)
  
  
  ## Convert the half from having 3 categories ("1st", "2nd", "OT")
  ##  into having just 2: ("1st", "2nd/OT")
  ## which makes sense from the end-goal perspective:
  ##  we draw a difference between the mere end of 1st half, and
  ##  the actual end of games (which is end of 2nd half, or OT) where the score is infinitely more important
  
  
  pbp_by_drive$drive_half_start <- ifelse(pbp_by_drive$drive_half_start %in% c("2nd", "OT"),
                                          "2nd/OT",
                                          pbp_by_drive$drive_half_start)
  
  
  # pbp_by_drive$drive_time_left_in_half <- pbp_by_drive$drive_time_minutes_start +
  #   pbp_by_drive$drive_time_seconds_start/60 +
  #   ifelse(pbp_by_drive$drive_qtr_start %in% c(1,3),
  #          15,
  #          0)
  
  
  ## Game ID & Score differential - need to just rename the variables
  pbp_by_drive <- pbp_by_drive %>%
    rename(game_id = GameID,
           score_diff_start = drive_ScoreDiff_start)
  
  
  
  pbp_by_drive.noNA <- na.omit(pbp_by_drive[, c("categ.score", "pos_team", "def_pos_team", relev.var.names.lagged, "game_id", "game_id_half", "pos.homefield", "complem.ind",
                                                "score_diff_start", "drive_time_left_in_half", "drive_half_start")] %>%
                                 mutate(pos_team = factor(pos_team),
                                        def_pos_team = factor(def_pos_team),
                                        game_id = factor(game_id),
                                        game_id_half = factor(game_id_half)))
  
  
  # if (stand == FALSE) {
  #   pbp_by_drive.noNA <- pbp_by_drive.noNA %>%
  #     mutate_if(is.numeric, scale)
  # }
  
  pbp_by_drive.noNA$complem.ind <- as.numeric(pbp_by_drive.noNA$complem.ind)
  
  #pbp_by_drive.noNA$lagged_takeaways.nonscor <- as.numeric(pbp_by_drive.noNA$lagged_takeaways.nonscor)
  pbp_by_drive.noNA$lagged_turnovers.nonscor <- as.numeric(pbp_by_drive.noNA$lagged_turnovers.nonscor)
  
  
  
  
  # ## To avoid issue with DROPPED LEVELS (NEW HERE):
  # pbp_by_drive.noNA$pos_team <- droplevels(pbp_by_drive.noNA$pos_team)
  # pbp_by_drive.noNA$def_pos_team <- droplevels(pbp_by_drive.noNA$def_pos_team)
  #
  # ## Setting up the contrasts so that the intercept represented a "league-average opponent"
  # ## (sum_i alpha_i = sum_j beta_j = 0)
  # contrasts(pbp_by_drive.noNA$pos_team) <- contr.sum(nlevels(pbp_by_drive.noNA$pos_team))
  # contrasts(pbp_by_drive.noNA$def_pos_team) <- contr.sum(nlevels(pbp_by_drive.noNA$def_pos_team))
  # colnames(contrasts(pbp_by_drive.noNA$pos_team)) <- rownames(contrasts(pbp_by_drive.noNA$pos_team))[-nrow(contrasts(pbp_by_drive.noNA$pos_team))]
  # colnames(contrasts(pbp_by_drive.noNA$def_pos_team)) <- rownames(contrasts(pbp_by_drive.noNA$def_pos_team))[-nrow(contrasts(pbp_by_drive.noNA$def_pos_team))]
  
  
  
  lm.obj <- lm(formula(paste0("as.numeric(categ.score) ~", paste0(c("pos_team", "def_pos_team", "pos.homefield", "complem.ind",
                                                                    # paste0(relev.var.names.lagged, ":complem.ind", sep="")
                                                                    paste0(c(relev.var.names.lagged[1], paste0(relev.var.names.lagged[1],":", relev.var.names.lagged[2])), ":complem.ind", sep="")
                                                                    , "score_diff_start", "drive_time_left_in_half", "drive_half_start"
                                                                    , "score_diff_start:drive_time_left_in_half", "score_diff_start:drive_half_start", "drive_time_left_in_half:drive_half_start"
  ),
  collapse = " + "), collapse =" ")),
  data=pbp_by_drive.noNA[, c(if(incl.pos_team) c("pos_team", "def_pos_team", "pos.homefield", "complem.ind",
                                                 "score_diff_start", "drive_time_left_in_half", "drive_half_start") else NULL,
                             relev.var.names.lagged,
                             "categ.score")])
  
  X <- model.matrix(lm.obj)[,-1]
  y <- pbp_by_drive.noNA$categ.score
  
  # Indices of the design matrix X to NOT penalize:
  ind.nonpen <- which(!str_detect(colnames(X), fixed("lagged")))
  penfact.vec <- rep(1, ncol(X))
  penfact.vec[ind.nonpen] <- 0
  
  
  #####
  ## Fitting the reduced selected model
  ## NON-PROPORTIONAL ODDS
  #####
  
  # ordnet.obj <- ordinalNet.mine(x = as.matrix(X), y = y, alpha=alpha.val, standardize = T,
  #                                 nFolds=n.folds,
  #                                 penaltyFactors = penfact.vec,
  #                                 family="cumulative",
  #                                 parallelTerms = T,
  #                                 nonparallelTerms = T,
  #                                 nonparallel.categ = c(FALSE, FALSE, TRUE, FALSE),
  #                                 nonparallel.factor = str_detect(colnames(X), "lagged"),
  #                                 lambdaVals = 0
  #                                 #, printIter=TRUE
  # )
  
  ordnet.obj <- ordinalNet.mine(x = as.matrix(X), y = y, alpha=alpha.val, standardize = T,
                                penaltyFactors = penfact.vec,
                                family="cumulative",
                                parallelTerms = T,
                                nonparallelTerms = T,
                                nonparallel.categ = c(FALSE, FALSE, TRUE, FALSE),
                                nonparallel.factor = str_detect(colnames(X), "lagged"),
                                lambdaVals = 0,
                                printIter=TRUE
  )
  
  
  ######
  ## NO COMPLEMENTARY (only strength-of-schedule, homefield adjustment, and in-game factors like score diff, time left, half)
  ######
  
  
  ## First: basic lm fit, just to get the design matrix X & response y
  lm.no.complem.obj <- lm(# as.numeric(categ.score) ~ pos_team + def_pos_team + pos.homefield + ,
    formula(paste0("as.numeric(categ.score) ~", paste0(c("pos_team", "def_pos_team", "pos.homefield"  # "complem.ind", paste0(relev.var.names.lagged, ":complem.ind", sep="")
                                                         , "score_diff_start", "drive_time_left_in_half", "drive_half_start"
                                                         , "score_diff_start:drive_time_left_in_half", "score_diff_start:drive_half_start", "drive_time_left_in_half:drive_half_start"
    ),
    collapse = " + "), collapse =" ")),
    data=pbp_by_drive.noNA)
  
  X.no.complem <- model.matrix(lm.no.complem.obj)[,-1]
  y.no.complem <- pbp_by_drive.noNA$categ.score
  
  ind.nonpen <- which(!str_detect(colnames(X.no.complem), fixed("lagged")))
  penfact.vec <- rep(1, ncol(X.no.complem))
  penfact.vec[ind.nonpen] <- 0
  
  
  ordnet.no.complem.obj <- ordinalNet.mine(x = X.no.complem, y = y.no.complem, alpha=alpha.val, standardize = T,
                                           # nFolds = n.folds,
                                           # folds=common.folds,
                                           penaltyFactors = penfact.vec,
                                           family="cumulative",
                                           parallelTerms = T,
                                           nonparallelTerms = F,
                                           lambdaVals = 0
                                           , printIter=TRUE
  )
  
  ###
  # SAVING THE "ordinalNet" FITS
  ###
  ordnet.fits[[as.character(year)]] <- list(with.complem = ordnet.obj
                                            ,no.complem = ordnet.no.complem.obj
                                            #, with.complem.paral.only = ordnet.paral.obj
  )
  
  
  #############
  #############
  ###  DOING EXPECTED POINT CALCULATIONS
  #############
  #############
  
  ordnet.obj <- ordnet.fits[[as.character(year)]]$with.complem
  
  ####
  # Making expected point predictions for each team.
  ####
  
  # Saving the matrix of contrasts for offensive and defensive margin parameters.
  contr.mat.pos_team <- contrasts(pbp_by_drive.noNA$pos_team)
  contr.mat.def_pos_team <- contrasts(pbp_by_drive.noNA$def_pos_team)
  
  # Calculating the mean vector for the values of all complementary statistics,
  # to project the performances onto the league-average complementary unit.
  # mean.vec <- as.matrix(t(apply(pbp_by_drive.noNA_for_final_df[, relev.var.names.lagged],
  #                               2,
  #                               mean)))
  # mean.vec <- mean(pbp_by_drive.noNA[, relev.var.names.lagged])
  
  ######
  ### Projecting into COMMON OPPONENT ONLY (NO COMPLEMENTARY STATS):
  ######
  #   (Making the predictions for EACH OBSERVATION, where we:
  #     * just REPLACE THE OPPONENT WITH A "LEAGUE-AVERAGE" OPPONENT
  #     * while also getting the AVERAGE HOMEFIELD VALUE (to account for cases of imbalanced schedules)
  # )
  
  # ordnet.fits[[as.character(year)]]$with.complem
  # ordnet.fits[[as.character(year)]]$no.complem
  
  # off.proj.mat <- ordnet.fits[[as.character(year)]]$no.complem$args$x
  off.proj.mat <- X.no.complem
  off.proj.mat[, str_detect(colnames(off.proj.mat), "def_pos")] <- 0
  off.proj.mat[, "pos.homefield"] <- mean(off.proj.mat[, "pos.homefield"])
  
  
  pbp_by_drive.noNA <- data.frame(pbp_by_drive.noNA, 
                                  Offense.Avg.Points.No.Complem = predict.ordinalNet.mine(ordnet.fits[[as.character(year)]]$no.complem,
                                                                                          newx = off.proj.mat)%*% c(-7,-2,0,3,7))
  
  
  def.proj.mat <- X.no.complem
  def.proj.mat[, str_detect(colnames(def.proj.mat), "off_pos")] <- 0
  def.proj.mat[, "pos.homefield"] <- mean(def.proj.mat[, "pos.homefield"])
  
  pbp_by_drive.noNA <- data.frame(pbp_by_drive.noNA, 
                                  Defense.Avg.Points.No.Complem = predict.ordinalNet.mine(ordnet.fits[[as.character(year)]]$no.complem,
                                                                                          newx = def.proj.mat)%*% c(-7,-2,0,3,7))
  
  
  #######
  ### Projecting into COMMON OPPONENT AND THE COMPLEMENTARY STATS:
  #######
  
  #   (Making the predictions for EACH OBSERVATION, where we:
  #     * REPLACE THE OPPONENT WITH A "LEAGUE-AVERAGE" OPPONENT
  #     * while also getting the AVERAGE HOMEFIELD VALUE (to account for cases of imbalanced schedules)
  #     * Replace the takeaways & yards with AVERAGE
  # )
  
  off.proj.mat <- X
  off.proj.mat[, str_detect(colnames(off.proj.mat), "def_pos")] <- 0
  off.proj.mat[, "pos.homefield"] <- mean(off.proj.mat[, "pos.homefield"])
  # off.proj.mat[, "complem.ind:lagged_off.yards_gained"] <- ifelse(off.proj.mat[, "complem.ind"] != 0,
  #                                                                 mean(off.proj.mat[, "complem.ind:lagged_off.yards_gained"][off.proj.mat[, "complem.ind"] != 0]),
  #                                                                 0)
  
  off.proj.mat[, "complem.ind:lagged_turnovers.nonscor:lagged_start_pos_post_turnover"] <- ifelse(# off.proj.mat[, "complem.ind:lagged_turnovers.nonscor"] != 0,
    off.proj.mat[, "complem.ind"] != 0,
    mean(off.proj.mat[, "complem.ind:lagged_turnovers.nonscor:lagged_start_pos_post_turnover"][off.proj.mat[, "complem.ind"] != 0]),
    0)
  off.proj.mat[, "complem.ind:lagged_turnovers.nonscor"] <- ifelse(off.proj.mat[, "complem.ind"] != 0,
                                                                   mean(off.proj.mat[, "complem.ind:lagged_turnovers.nonscor"][off.proj.mat[, "complem.ind"] != 0]),
                                                                   0)
  
  
  
  pbp_by_drive.noNA <- data.frame(pbp_by_drive.noNA, 
                                  Offense.Avg.Points.Avg.Takeaways = predict.ordinalNet.mine(ordnet.fits[[as.character(year)]]$with.complem,
                                                                                             newx = off.proj.mat)%*% c(-7,-2,0,3,7))
  
  
  def.proj.mat <- X
  def.proj.mat[, str_detect(colnames(def.proj.mat), "off_pos")] <- 0
  def.proj.mat[, "pos.homefield"] <- mean(def.proj.mat[, "pos.homefield"])
  # def.proj.mat[, "complem.ind:lagged_def.yards_gained"] <- ifelse(def.proj.mat[, "complem.ind"] != 0,
  #                                                                 mean(def.proj.mat[, "complem.ind:lagged_def.yards_gained"][def.proj.mat[, "complem.ind"] != 0]),
  #                                                                 0)
  
  def.proj.mat[, "complem.ind:lagged_turnovers.nonscor:lagged_start_pos_post_turnover"] <- ifelse(# def.proj.mat[, "complem.ind:lagged_turnovers.nonscor"] != 0,
    def.proj.mat[, "complem.ind"] != 0,
    mean(def.proj.mat[, "complem.ind:lagged_turnovers.nonscor:lagged_start_pos_post_turnover"][def.proj.mat[, "complem.ind"] != 0]),
    0)
  def.proj.mat[, "complem.ind:lagged_turnovers.nonscor"] <- ifelse(def.proj.mat[, "complem.ind"] != 0,
                                                                   mean(def.proj.mat[, "complem.ind:lagged_turnovers.nonscor"][def.proj.mat[, "complem.ind"] != 0]),
                                                                   0)
  
  
  
  pbp_by_drive.noNA <- data.frame(pbp_by_drive.noNA, 
                                  Defense.Avg.Points.Avg.Takeaways = predict.ordinalNet.mine(ordnet.fits[[as.character(year)]]$with.complem,
                                                                                             newx = def.proj.mat)%*% c(-7,-2,0,3,7))
  
  
  
  
  #######
  ### Projecting into COMMON OPPONENT AND THE COMPLEMENTARY STATS,
  ##    WITH TAKEAWAY
  #######
  
  #   (Making the predictions for EACH OBSERVATION, where we:
  #     * REPLACE THE OPPONENT WITH A "LEAGUE-AVERAGE" OPPONENT
  #     * while also getting the AVERAGE HOMEFIELD VALUE (to account for cases of imbalanced schedules)
  #     * Replace turnovers:starpos with 1*mean(starpos for the case of turnover) (so, mean(turnovers.starpos[turnovers==1]))
  #     * Replace turnovers with 1
  # )
  off.proj.mat <- X
  off.proj.mat[, str_detect(colnames(off.proj.mat), "def_pos")] <- 0
  off.proj.mat[, "pos.homefield"] <- mean(off.proj.mat[, "pos.homefield"])
  # off.proj.mat[, "complem.ind:lagged_off.yards_gained"] <- ifelse(off.proj.mat[, "complem.ind"] != 0,
  #                                                                 mean(off.proj.mat[, "complem.ind:lagged_off.yards_gained"][off.proj.mat[, "complem.ind"] != 0]),
  #                                                                 0)
  
  off.proj.mat[, "complem.ind:lagged_turnovers.nonscor:lagged_start_pos_post_turnover"] <- ifelse(# off.proj.mat[, "complem.ind:lagged_turnovers.nonscor"] != 0,
    off.proj.mat[, "complem.ind"] != 0,
    mean(off.proj.mat[, "complem.ind:lagged_turnovers.nonscor:lagged_start_pos_post_turnover"][off.proj.mat[, "complem.ind:lagged_turnovers.nonscor"] != 0]),
    0)
  off.proj.mat[, "complem.ind:lagged_turnovers.nonscor"] <- ifelse(off.proj.mat[, "complem.ind"] != 0,
                                                                   1,
                                                                   0)
  
  
  pbp_by_drive.noNA <- data.frame(pbp_by_drive.noNA, 
                                  Offense.Avg.Points.With.Takeaway = predict.ordinalNet.mine(ordnet.fits[[as.character(year)]]$with.complem,
                                                                                             newx = off.proj.mat)%*% c(-7,-2,0,3,7))
  
  
  def.proj.mat <- X
  def.proj.mat[, str_detect(colnames(def.proj.mat), "off_pos")] <- 0
  def.proj.mat[, "pos.homefield"] <- mean(def.proj.mat[, "pos.homefield"])
  # def.proj.mat[, "complem.ind:lagged_def.yards_gained"] <- ifelse(def.proj.mat[, "complem.ind"] != 0,
  #                                                                 mean(def.proj.mat[, "complem.ind:lagged_def.yards_gained"][def.proj.mat[, "complem.ind"] != 0]),
  #                                                                 0)
  
  def.proj.mat[, "complem.ind:lagged_turnovers.nonscor:lagged_start_pos_post_turnover"] <- ifelse(# def.proj.mat[, "complem.ind:lagged_turnovers.nonscor"] != 0,
    def.proj.mat[, "complem.ind"] != 0,
    mean(def.proj.mat[, "complem.ind:lagged_turnovers.nonscor:lagged_start_pos_post_turnover"][def.proj.mat[, "complem.ind:lagged_turnovers.nonscor"] != 0]),
    0)
  def.proj.mat[, "complem.ind:lagged_turnovers.nonscor"] <- ifelse(def.proj.mat[, "complem.ind"] != 0,
                                                                   1,
                                                                   0)
  
  
  pbp_by_drive.noNA <- data.frame(pbp_by_drive.noNA, 
                                  Defense.Avg.Points.With.Takeaway = predict.ordinalNet.mine(ordnet.fits[[as.character(year)]]$with.complem,
                                                                                             newx = def.proj.mat)%*% c(-7,-2,0,3,7))
  
  
  
  
  #######
  ### Projecting into COMMON OPPONENT AND THE COMPLEMENTARY STATS,
  ##   NO TAKEAWAY
  #######
  
  #   (Making the predictions for EACH OBSERVATION, where we:
  #     * REPLACE THE OPPONENT WITH A "LEAGUE-AVERAGE" OPPONENT
  #     * while also getting the AVERAGE HOMEFIELD VALUE (to account for cases of imbalanced schedules)
  #     * Replace turnovers:starpos with 0
  #     * Replace turnovers with 0
  # )
  off.proj.mat <- X
  off.proj.mat[, str_detect(colnames(off.proj.mat), "def_pos")] <- 0
  off.proj.mat[, "pos.homefield"] <- mean(off.proj.mat[, "pos.homefield"])
  # off.proj.mat[, "complem.ind:lagged_off.yards_gained"] <- ifelse(off.proj.mat[, "complem.ind"] != 0,
  #                                                                 mean(off.proj.mat[, "complem.ind:lagged_off.yards_gained"][off.proj.mat[, "complem.ind"] != 0]),
  #                                                                 0)
  
  off.proj.mat[, "complem.ind:lagged_turnovers.nonscor:lagged_start_pos_post_turnover"] <- 0 
  off.proj.mat[, "complem.ind:lagged_turnovers.nonscor"] <- 0
  
  
  pbp_by_drive.noNA <- data.frame(pbp_by_drive.noNA, 
                                  Offense.Avg.Points.No.Takeaway = predict.ordinalNet.mine(ordnet.fits[[as.character(year)]]$with.complem,
                                                                                           newx = off.proj.mat)%*% c(-7,-2,0,3,7))
  
  
  def.proj.mat <- X
  def.proj.mat[, str_detect(colnames(def.proj.mat), "off_pos")] <- 0
  def.proj.mat[, "pos.homefield"] <- mean(def.proj.mat[, "pos.homefield"])
  # def.proj.mat[, "complem.ind:lagged_def.yards_gained"] <- ifelse(def.proj.mat[, "complem.ind"] != 0,
  #                                                                 mean(def.proj.mat[, "complem.ind:lagged_def.yards_gained"][def.proj.mat[, "complem.ind"] != 0]),
  #                                                                 0)
  
  def.proj.mat[, "complem.ind:lagged_turnovers.nonscor:lagged_start_pos_post_turnover"] <- 0
  def.proj.mat[, "complem.ind:lagged_turnovers.nonscor"] <- 0
  
  
  pbp_by_drive.noNA <- data.frame(pbp_by_drive.noNA, 
                                  Defense.Avg.Points.No.Takeaway = predict.ordinalNet.mine(ordnet.fits[[as.character(year)]]$with.complem,
                                                                                           newx = def.proj.mat)%*% c(-7,-2,0,3,7))
  
  
  
  
  ### Projecting into COMMON OPPONENT, but NOT COMPLEM STATS, although THOSE WERE USED IN TRAINING !!!:
  #   (Making the predictions for EACH OBSERVATION, where we:
  #     * REPLACE THE OPPONENT WITH A "LEAGUE-AVERAGE" OPPONENT
  #     * while also getting the AVERAGE HOMEFIELD VALUE (to account for cases of imbalanced schedules)
  #     * !!! KEEP TAKEAWAYS, YDS - AS IS !!!
  # )
  
  # off.proj.mat <- ordnet.fits[[as.character(year)]]$with.complem$args$x
  off.proj.mat <- X
  off.proj.mat[, str_detect(colnames(off.proj.mat), "def_pos")] <- 0
  off.proj.mat[, "pos.homefield"] <- mean(off.proj.mat[, "pos.homefield"])
  
  
  pbp_by_drive.noNA <- data.frame(pbp_by_drive.noNA, 
                                  Offense.Avg.Points.With.Complem.But.As.Is = predict.ordinalNet.mine(ordnet.fits[[as.character(year)]]$with.complem,
                                                                                                      newx = off.proj.mat)%*% c(-7,-2,0,3,7))
  
  
  # def.proj.mat <- ordnet.fits[[as.character(year)]]$with.complem$args$x
  def.proj.mat <- X
  def.proj.mat[, str_detect(colnames(def.proj.mat), "off_pos")] <- 0
  def.proj.mat[, "pos.homefield"] <- mean(def.proj.mat[, "pos.homefield"])
  
  
  pbp_by_drive.noNA <- data.frame(pbp_by_drive.noNA, 
                                  Defense.Avg.Points.With.Complem.But.As.Is = predict.ordinalNet.mine(ordnet.fits[[as.character(year)]]$with.complem,
                                                                                                      newx = def.proj.mat)%*% c(-7,-2,0,3,7))
  
  
  ### Projecting into LEAGUE-AVERAGE COMPLEMENTARY UNIT, but NOT COMMON OPPONENT.. although SOS WAS USED IN TRAINING !!!:
  #   (Making the predictions for EACH OBSERVATION, where we:
  #     * REPLACE THE COMPLEMENTARY UNIT STUFF WITH LEAGUE AVG
  #     * while also getting the AVERAGE HOMEFIELD VALUE (to account for cases of imbalanced schedules)
  #     * !!! KEEP OPPONENT & EVERYTHING ELSE AS IS!
  # )
  off.proj.mat <- X
  # off.proj.mat[, str_detect(colnames(off.proj.mat), "def_pos")] <- 0
  off.proj.mat[, "pos.homefield"] <- mean(off.proj.mat[, "pos.homefield"])
  # off.proj.mat[, "complem.ind:lagged_off.yards_gained"] <- ifelse(off.proj.mat[, "complem.ind"] != 0,
  #                                                                 mean(off.proj.mat[, "complem.ind:lagged_off.yards_gained"][off.proj.mat[, "complem.ind"] != 0]),
  #                                                                 0)
  
  off.proj.mat[, "complem.ind:lagged_turnovers.nonscor:lagged_start_pos_post_turnover"] <- ifelse(# off.proj.mat[, "complem.ind:lagged_turnovers.nonscor"] != 0,
    off.proj.mat[, "complem.ind"] != 0,
    mean(off.proj.mat[, "complem.ind:lagged_turnovers.nonscor:lagged_start_pos_post_turnover"][off.proj.mat[, "complem.ind"] != 0]),
    0)
  off.proj.mat[, "complem.ind:lagged_turnovers.nonscor"] <- ifelse(off.proj.mat[, "complem.ind"] != 0,
                                                                   mean(off.proj.mat[, "complem.ind:lagged_turnovers.nonscor"][off.proj.mat[, "complem.ind"] != 0]),
                                                                   0)
  
  
  
  pbp_by_drive.noNA <- data.frame(pbp_by_drive.noNA, 
                                  Offense.Avg.Points.Avg.Takeaways.But.SOS.As.Is = predict.ordinalNet.mine(ordnet.fits[[as.character(year)]]$with.complem,
                                                                                                           newx = off.proj.mat)%*% c(-7,-2,0,3,7))
  
  
  def.proj.mat <- X
  # def.proj.mat[, str_detect(colnames(def.proj.mat), "off_pos")] <- 0
  def.proj.mat[, "pos.homefield"] <- mean(def.proj.mat[, "pos.homefield"])
  # def.proj.mat[, "complem.ind:lagged_def.yards_gained"] <- ifelse(def.proj.mat[, "complem.ind"] != 0,
  #                                                                 mean(def.proj.mat[, "complem.ind:lagged_def.yards_gained"][def.proj.mat[, "complem.ind"] != 0]),
  #                                                                 0)
  
  def.proj.mat[, "complem.ind:lagged_turnovers.nonscor:lagged_start_pos_post_turnover"] <- ifelse(# def.proj.mat[, "complem.ind:lagged_turnovers.nonscor"] != 0,
    def.proj.mat[, "complem.ind"] != 0,
    mean(def.proj.mat[, "complem.ind:lagged_turnovers.nonscor:lagged_start_pos_post_turnover"][def.proj.mat[, "complem.ind"] != 0]),
    0)
  def.proj.mat[, "complem.ind:lagged_turnovers.nonscor"] <- ifelse(def.proj.mat[, "complem.ind"] != 0,
                                                                   mean(def.proj.mat[, "complem.ind:lagged_turnovers.nonscor"][def.proj.mat[, "complem.ind"] != 0]),
                                                                   0)
  
  
  
  pbp_by_drive.noNA <- data.frame(pbp_by_drive.noNA, 
                                  Defense.Avg.Points.Avg.Takeaways.But.SOS.As.Is = predict.ordinalNet.mine(ordnet.fits[[as.character(year)]]$with.complem,
                                                                                                           newx = def.proj.mat)%*% c(-7,-2,0,3,7))
  
  
  
  ### Calculating the bootstrap per-drive point averages for each team
  pbp_by_drive.noNA$pts_scored_num <- ifelse(pbp_by_drive.noNA$categ.score == "Offensive TD", 
                                             7,
                                             ifelse(pbp_by_drive.noNA$categ.score == "Field Goal",
                                                    3, 
                                                    ifelse(pbp_by_drive.noNA$categ.score == "No Score",
                                                           0,
                                                           ifelse(pbp_by_drive.noNA$categ.score == "Safety",
                                                                  -2,
                                                                  -7))))
  
  ## Making sure we also keep the actual per-drive point averages
  

  
  
  projected.points.intercept[[as.character(year)]] <- pbp_by_drive.noNA %>%
    group_by(pos_team) %>%
    summarise(
      Offense.Avg.Points.Actual = mean(pts_scored_num),
      Offense.Avg.Points.No.Complem = mean(Offense.Avg.Points.No.Complem),
      Offense.Avg.Points.Avg.Takeaways = mean(Offense.Avg.Points.Avg.Takeaways),
      Offense.Avg.Points.With.Takeaway = mean(Offense.Avg.Points.With.Takeaway),
      Offense.Avg.Points.No.Takeaway = mean(Offense.Avg.Points.No.Takeaway),
      Offense.Avg.Points.With.Complem.But.As.Is = mean(Offense.Avg.Points.With.Complem.But.As.Is),
      Offense.Avg.Points.Avg.Takeaways.But.SOS.As.Is = mean(Offense.Avg.Points.Avg.Takeaways.But.SOS.As.Is),
      Offense.Games.Included = length(unique(game_id)),
      Offense.Halves.Included =length(unique(game_id_half)),
      Offense.Drives.Included = n()
    ) %>% left_join(pbp_by_drive.noNA %>% 
                      group_by(def_pos_team) %>%
                      summarise(
                        Defense.Avg.Points.Actual = mean(pts_scored_num),
                        Defense.Avg.Points.No.Complem = mean(Defense.Avg.Points.No.Complem),
                        Defense.Avg.Points.Avg.Takeaways = mean(Defense.Avg.Points.Avg.Takeaways),
                        Defense.Avg.Points.With.Takeaway = mean(Defense.Avg.Points.With.Takeaway),
                        Defense.Avg.Points.No.Takeaway = mean(Defense.Avg.Points.No.Takeaway),
                        Defense.Avg.Points.With.Complem.But.As.Is = mean(Defense.Avg.Points.With.Complem.But.As.Is),
                        Defense.Avg.Points.Avg.Takeaways.But.SOS.As.Is = mean(Defense.Avg.Points.Avg.Takeaways.But.SOS.As.Is),
                        Defense.Games.Included = length(unique(game_id)),
                        Defense.Halves.Included =length(unique(game_id_half)),
                        Defense.Drives.Included = n(),
                      ),
                    by = c("pos_team" = "def_pos_team")) %>%
    rename(Team = pos_team)
  
  
}


save(projected.points.intercept, file= paste0("RESUBMISSION_NFL_W_START_POS_ORDNET_projected.points.intercept.RData"))
save(ordnet.fits, file=paste0("RESUBMISSION_NFL_W_START_POS_ORDNET_ordnet.fits.RData"))