## For the paper.

#####
## NFL
##
## 10-fold CV to compare INCLUDING COMPLEMENTARY STATS vs NOT INCLUDING THEM
## For regular linear regression (not ordinal)
## [Calculates an object to be fed to "PAPER_RESubmission_11p6_LINEAR_VS_ORDINAL_BOTH_CFB_AND_COLLEGE_MAE_PLOTS.R"]
######

## Seed for reproducibility of CV
set.seed(1)

library(ordinalNet)
library(boot)

# Loading the enhanced ordinalNet code.
source("Submission_0_ordinalNet_package_source_code_enhanced.R")



library(tidyverse)
library(car)
library(fuzzyjoin)
library(sure)
library(ordinal)
library(ggplot2)
library(ggfortify)


MAE <- TRUE

if (MAE){
  cost.fun <- function(y, pi) {
    mean(abs(y - pi))
  }
} else {
  cost.fun <- function(y, pi){
    sqrt(mean((y-pi)^2))
  }
}


# We will only focus on the complementary statistics that were consistently picked
# (yards gained and non-scoring takeaways)
all.variables <- FALSE

# We will be combining the yards for offense and special teams returns.
yds.combine <- TRUE




## alpha trade-off value
alpha.val <- 0.99

## # of CV folds
n.folds <- 10

## We include the POS_TEAM/DEF_POS_TEAM/HOMEFIELD
incl.pos_team <- TRUE


projected.points <- NULL
projected.points.intercept <- NULL
ordnet.fits <- NULL


CV.results.with.complem <- CV.results.no.complem <- CV.results.nothing <- CV.results.only.complem <- NULL


for (year in 2009:2017){
  
  print("Year:")
  print(year)
  
  
  pbp_by_drive <- read.csv("NFL_2009_2017_Drive_by_Drive_Data_Cleaned.csv") %>%
    filter(Season == year)
  
  
  ## Just make onside kick stuff a Fumble, for simplicity
  pbp_by_drive$drive_Outcome[pbp_by_drive$drive_Outcome == "Onside Kick Recovered / Fumble"] <- "Fumble"
  
  
  table(pbp_by_drive$drive_Outcome)
  
  
  ## Getting an ID variable
  pbp_by_drive$game_id_half <- paste0(pbp_by_drive$GameID, "-", pbp_by_drive$drive_half_start)
  
  ## Non-scoring FORCED TOs, such as picks, fumbles, on-side kick recovery
  pbp_by_drive$takeaways.nonscor <- pbp_by_drive$drive_Outcome %in% c("Fumble", # "Fumble Recovery (Opponent)",
                                                                      "Interception" # "Interception Return",
                                                                      # "Kickoff Team Fumble Recovery",
                                                                      # "Punt Team Fumble Lost",
                                                                      #  "Blocked Punt Team Fumble Lost",
                                                                      #  "On-Side Kick Lost"
  )
  
  ## Any TOs, including FG misses/blocks, turnover on downs
  pbp_by_drive$turnovers.nonscor <- (pbp_by_drive$takeaways.nonscor | 
                                       pbp_by_drive$drive_Outcome %in% c(# "Blocked Field Goal",
                                         # "Field Goal Missed",
                                         "Missed Field Goal", # "Missed Field Goal Return",
                                         "Turnover on Downs" #, "Downs Turnover"
                                       )
  )
  
  pbp_by_drive$defensive.score <- pbp_by_drive$drive_Outcome %in% c("Defensive Touchdown")
  
  
  ## Punts or safeties (both result in turning the ball over via a 'punting motion', although the latter also has -2 pts)
  pbp_by_drive$punt.safety <- pbp_by_drive$drive_Outcome %in% c("Punt", "Safety")
  
  ## Number of positive runs
  # pbp_by_drive$n.positive.runs <- pbp_by_drive$n.rush - pbp_by_drive$n.stuffed.runs
  
  ## Special team return variables:
  pbp_by_drive$yds_ST_return_net <- pbp_by_drive$ST.return.yards.net
  
  
  ####
  ## Combining the yards for offense and special teams.
  ####
  if (yds.combine == TRUE){
    
    # pbp_by_drive$off.yards_gained <- pbp_by_drive$off.yards_gained + pbp_by_drive$yds_ST_return
    pbp_by_drive$off.yards_gained <- pbp_by_drive$off.ST.yards.gained
  }
  
  
  #####
  ## Creating the indicator variable for "complementary drives", as in - anything but
  #     1) Kickoffs at the start of halves, 
  #     2) Drives directly after a defensive touchdown.
  #####
  
  pbp_by_drive$complem.ind <- ifelse(lag(pbp_by_drive$game_id_half) == pbp_by_drive$game_id_half,
                                     ifelse(lag(pbp_by_drive$pos_team) != pbp_by_drive$pos_team,
                                            1,
                                            0),
                                     1)
  pbp_by_drive$complem.ind[1] <- 0   # Cleaning up the "NA" generated by the first lag
  
  pbp_by_drive$n.negative.plays.with.penalties <- pbp_by_drive$n.negative.plays
  
  
  pbp_by_drive$score_pts_by_text <- pbp_by_drive$pts.scored
  
  # There was always an issue with keeping track of extra point for defensive TD, 
  # so gotta switch from "-6" to "-7"
  
  pbp_by_drive$score_pts_by_text[pbp_by_drive$score_pts_by_text == -6] <- -7
  
  
  
  ## All the complementary statistics under consideration
  relev.var.names <- c("n.completions", "n.incompletions", "n.stuffed.runs", "n.positive.runs", "n.negative.plays.with.penalties",
                       "off.yards_gained",
                       "score_pts_by_text",
                       "yds_ST_return_net", 
                       # "yds_ST_return",
                       "n.sacks", "n.fumbles",
                       "first.downs.gained", "third.downs.converted",
                       "takeaways.nonscor", "turnovers.nonscor",
                       "punt.safety"
  )
  
  
  # Initializing a lagged variable set
  pbp_by_drive_lag_vars <- data.frame(game_id_half = pbp_by_drive$game_id_half,
                                      pos_team = pbp_by_drive$pos_team,
                                      # pbp_by_drive[, 8:ncol(pbp_by_drive)]
                                      pbp_by_drive[, relev.var.names]
  )
  
  
  # For numerical variables, creating their lagged values, 
  for (c.ind in 3:ncol(pbp_by_drive_lag_vars)){
    pbp_by_drive_lag_vars[, c.ind] <- lag(pbp_by_drive_lag_vars[, c.ind])
    pbp_by_drive_lag_vars[1, c.ind] <- pbp_by_drive_lag_vars[2, c.ind] # For the initial NA value
  }
  
  # Making the variable names for lagged values explicit (adding "lagged" to them)
  colnames(pbp_by_drive_lag_vars)[3:ncol(pbp_by_drive_lag_vars)] <- paste0("lagged_", colnames(pbp_by_drive_lag_vars)[3:ncol(pbp_by_drive_lag_vars)])
  
  # Merging the lagged values into original data set
  pbp_by_drive <- data.frame(pbp_by_drive, pbp_by_drive_lag_vars[,-1])
  
  
  
  ## If we combine yards, then DROP the "yds_ST_return"
  #  if (yds.combine) relev.var.names <- relev.var.names[relev.var.names != "yds_ST_return"]
  
  
  pbp_by_drive$lagged_start_pos_post_turnover <- ifelse(pbp_by_drive$lagged_turnovers.nonscor == 1,
                                                        log(c(100-pbp_by_drive$off.ST.start.pos +1)),
                                                        mean(log(100-pbp_by_drive$off.ST.start.pos[pbp_by_drive$lagged_turnovers.nonscor == 1] + 1)))
  
  
  
  
  
  
  #######
  ## Complementary statistics to be included in the model for testing:
  #######
  
  # relev.var.names.lagged <- paste0("lagged_", relev.var.names)
  
    if (all.variables){
      relev.var.names.lagged <- paste0("lagged_", relev.var.names)
    } else {
      # relev.var.names <- c("off.yards_gained",
      #                      "takeaways.nonscor")
      relev.var.names.lagged <- c("lagged_turnovers.nonscor",
                                  "lagged_start_pos_post_turnover")
    }
  
  ## Defining the categorical ordinal scoring outcome variable
  
  pbp_by_drive$categ.score <- ifelse(pbp_by_drive$score_pts_by_text %in% c(6,7,8),
                                     "Offensive TD",
                                     ifelse(pbp_by_drive$score_pts_by_text == 3,
                                            "Field Goal",
                                            ifelse(pbp_by_drive$score_pts_by_text == -2,
                                                   "Safety",
                                                   ifelse(pbp_by_drive$score_pts_by_text == 2,
                                                          NA,
                                                          ifelse(pbp_by_drive$score_pts_by_text %in% c(-6,-7,-8),
                                                                 "Defensive TD",
                                                                 "No Score")))))
  
  
  pbp_by_drive$score_pts <- ifelse(pbp_by_drive$score_pts_by_text %in% c(6,7,8),
                                   7,
                                   ifelse(pbp_by_drive$score_pts_by_text == 3,
                                          3,
                                          ifelse(pbp_by_drive$score_pts_by_text == -2,
                                                 -2,
                                                 ifelse(pbp_by_drive$score_pts_by_text == 2,
                                                        NA,
                                                        ifelse(pbp_by_drive$score_pts_by_text %in% c(-6,-7,-8),
                                                               -7,
                                                               0)))))
  
  pbp_by_drive$categ.score <- factor(pbp_by_drive$categ.score,
                                     ordered=T,
                                     levels = c("Defensive TD", "Safety", "No Score", "Field Goal", "Offensive TD"))
  
  
  
  
  
  ###########
  ###########
  ### Calculating PROJECTED POINTS for EACH TEAM
  ###########
  ###########
  
  ## Time left in half
  # "drive_TimeSecs_start" - doesn't look good, a bunch of negative values, etc..
  # Just using the "drive_time_start", which looks way more reliable
  
  pbp_by_drive$drive_time_left_in_half <-  as.numeric(substr(pbp_by_drive$drive_time_start, 1, 2)) +
    as.numeric(substr(pbp_by_drive$drive_time_start, 4, 5))/60 +
    ifelse(pbp_by_drive$drive_qtr_start %in% c(1,3),
           15,
           0)
  
  
  ## Convert the half from having 3 categories ("1st", "2nd", "OT") 
  ##  into having just 2: ("1st", "2nd/OT")
  ## which makes sense from the end-goal perspective: 
  ##  we draw a difference between the mere end of 1st half, and 
  ##  the actual end of games (which is end of 2nd half, or OT) where the score is infinitely more important
  
  
  pbp_by_drive$drive_half_start <- ifelse(pbp_by_drive$drive_half_start %in% c("2nd", "OT"),
                                          "2nd/OT",
                                          pbp_by_drive$drive_half_start)
  
  
  # pbp_by_drive$drive_time_left_in_half <- pbp_by_drive$drive_time_minutes_start + 
  #   pbp_by_drive$drive_time_seconds_start/60 +
  #   ifelse(pbp_by_drive$drive_qtr_start %in% c(1,3),
  #          15,
  #          0)
  
  
  ## Game ID & Score differential - need to just rename the variables
  pbp_by_drive <- pbp_by_drive %>% 
    rename(game_id = GameID,
           score_diff_start = drive_ScoreDiff_start)
  
  
  
  pbp_by_drive.noNA <- na.omit(pbp_by_drive[, c("score_pts", "pos_team", "def_pos_team", relev.var.names.lagged, "game_id", "game_id_half", "pos.homefield", "complem.ind",
                                                "score_diff_start", "drive_time_left_in_half", "drive_half_start")] %>%
                                 mutate(pos_team = factor(pos_team),
                                        def_pos_team = factor(def_pos_team),
                                        game_id = factor(game_id),
                                        game_id_half = factor(game_id_half)))
  
  
    # if (stand == FALSE) {
    #   pbp_by_drive.noNA <- pbp_by_drive.noNA %>%
    #     mutate_if(is.numeric, scale)
    # }

    pbp_by_drive.noNA$complem.ind <- as.numeric(pbp_by_drive.noNA$complem.ind)

    #pbp_by_drive.noNA$lagged_takeaways.nonscor <- as.numeric(pbp_by_drive.noNA$lagged_takeaways.nonscor)
    pbp_by_drive.noNA$lagged_turnovers.nonscor <- as.numeric(pbp_by_drive.noNA$lagged_turnovers.nonscor)

  
  
  ## To avoid issue with DROPPED LEVELS (NEW HERE):
  pbp_by_drive.noNA$pos_team <- droplevels(pbp_by_drive.noNA$pos_team)
  pbp_by_drive.noNA$def_pos_team <- droplevels(pbp_by_drive.noNA$def_pos_team)
  
  ## Setting up the contrasts so that the intercept represented a "league-average opponent"
  ## (sum_i alpha_i = sum_j beta_j = 0)
  contrasts(pbp_by_drive.noNA$pos_team) <- contr.sum(nlevels(pbp_by_drive.noNA$pos_team))
  contrasts(pbp_by_drive.noNA$def_pos_team) <- contr.sum(nlevels(pbp_by_drive.noNA$def_pos_team))
  colnames(contrasts(pbp_by_drive.noNA$pos_team)) <- rownames(contrasts(pbp_by_drive.noNA$pos_team))[-nrow(contrasts(pbp_by_drive.noNA$pos_team))]
  colnames(contrasts(pbp_by_drive.noNA$def_pos_team)) <- rownames(contrasts(pbp_by_drive.noNA$def_pos_team))[-nrow(contrasts(pbp_by_drive.noNA$def_pos_team))]
  
  
  
  
  #########
  ## WITH EVERYTHING
  ##########
  
  # No explicit setting of folds, so maybe just use the YEAR to be consistent
  set.seed(year)
  
  lm.obj <- glm(formula(paste0("score_pts ~", paste0(c("pos_team", "def_pos_team", "pos.homefield", "complem.ind", 
                                                       # paste0(relev.var.names.lagged, ":complem.ind", sep="")
                                                       paste0(c(relev.var.names.lagged[1], paste0(relev.var.names.lagged[1],":", relev.var.names.lagged[2])), ":complem.ind", sep="")
                                                                    , "score_diff_start", "drive_time_left_in_half", "drive_half_start"
                                                                    , "score_diff_start:drive_time_left_in_half", "score_diff_start:drive_half_start", "drive_time_left_in_half:drive_half_start"
  ),
  collapse = " + "), collapse =" ")),
  data=pbp_by_drive.noNA[, c(if(incl.pos_team) c("pos_team", "def_pos_team", "pos.homefield", "complem.ind", 
                                                 "score_diff_start", "drive_time_left_in_half", "drive_half_start") else NULL,
                             relev.var.names.lagged,
                             "score_pts")])
  


 cv.obj <- cv.glm(data = pbp_by_drive.noNA[, c(if(incl.pos_team) c("pos_team", "def_pos_team", "pos.homefield", "complem.ind", 
                                                          "score_diff_start", "drive_time_left_in_half", "drive_half_start") else NULL,
                                      relev.var.names.lagged,
                                      "score_pts")],
         lm.obj,
         K=10,
         cost = cost.fun)
  
 CV.results.with.complem <- rbind(CV.results.with.complem,
                                  data.frame(Year = year,
                                             RMSE = cv.obj$delta[1],
                                             SE = sqrt(cv.obj$delta[2]/nrow(pbp_by_drive.noNA))))
 
 
 
 
 #######
 ### NO COMPLEMENTARY STUFF (just game context & SOS)
 #######
 
 
 # No explicit setting of folds, so maybe just use the YEAR to be consistent
 set.seed(year)
 
 lm.no.complem.obj <- glm(formula(paste0("score_pts ~", paste0(c("pos_team", "def_pos_team", "pos.homefield" #, "complem.ind", paste0(relev.var.names.lagged, ":complem.ind", sep="")
                                                              , "score_diff_start", "drive_time_left_in_half", "drive_half_start"
                                                              , "score_diff_start:drive_time_left_in_half", "score_diff_start:drive_half_start", "drive_time_left_in_half:drive_half_start"
 ),
 collapse = " + "), collapse =" ")),
 data=pbp_by_drive.noNA[, c(if(incl.pos_team) c("pos_team", "def_pos_team", "pos.homefield", "complem.ind", 
                                                "score_diff_start", "drive_time_left_in_half", "drive_half_start") else NULL,
                            relev.var.names.lagged,
                            "score_pts")])
 
 
 cv.obj <- cv.glm(data = pbp_by_drive.noNA[, c(if(incl.pos_team) c("pos_team", "def_pos_team", "pos.homefield", # "complem.ind", 
                                                                   "score_diff_start", "drive_time_left_in_half", "drive_half_start") else NULL,
                                               # relev.var.names.lagged,
                                               "score_pts")],
                  lm.no.complem.obj,
                  K=10,
                  cost=cost.fun)
 
 CV.results.no.complem <- rbind(CV.results.no.complem,
                                  data.frame(Year = year,
                                             RMSE = cv.obj$delta[1],
                                             SE = sqrt(cv.obj$delta[2]/nrow(pbp_by_drive.noNA))))
 
 
 
 #########
 ## WITH NOTHING but game context (no SOS, no complementary)
 ##########
 
 # No explicit setting of folds, so maybe just use the YEAR to be consistent
 set.seed(year)
 
 lm.nothing.obj <- glm(formula(paste0("score_pts ~", paste0(c(# "pos_team", "def_pos_team", 
                                                              "pos.homefield"
                                                              # , "complem.ind", paste0(relev.var.names.lagged, ":complem.ind", sep="")
                                                              , "score_diff_start", "drive_time_left_in_half", "drive_half_start"
                                                              , "score_diff_start:drive_time_left_in_half", "score_diff_start:drive_half_start", "drive_time_left_in_half:drive_half_start"
 ),
 collapse = " + "), collapse =" ")),
 data=pbp_by_drive.noNA[, c(if(incl.pos_team) c("pos_team", "def_pos_team", "pos.homefield", "complem.ind", 
                                                "score_diff_start", "drive_time_left_in_half", "drive_half_start") else NULL,
                            relev.var.names.lagged,
                            "score_pts")])
 
 
 
 cv.obj <- cv.glm(data = pbp_by_drive.noNA[, c(if(incl.pos_team) c(# "pos_team", "def_pos_team", 
                                                                   "pos.homefield", #"complem.ind", 
                                                                   "score_diff_start", "drive_time_left_in_half", "drive_half_start") else NULL,
                                               # relev.var.names.lagged,
                                               "score_pts")],
                  lm.nothing.obj,
                  K=10,
                  cost = cost.fun)
 
 CV.results.nothing <- rbind(CV.results.nothing,
                                  data.frame(Year = year,
                                             RMSE = cv.obj$delta[1],
                                             SE = sqrt(cv.obj$delta[2]/nrow(pbp_by_drive.noNA))))
 
 
 
 #########
 ## WITH EVERYTHING
 ##########
 
 # No explicit setting of folds, so maybe just use the YEAR to be consistent
 set.seed(year)
 
 lm.only.complem.obj <- glm(formula(paste0("score_pts ~", paste0(c(# "pos_team", "def_pos_team", 
                                                                           "pos.homefield", 
                                                                           "complem.ind", 
                                                                           paste0(c(relev.var.names.lagged[1], paste0(relev.var.names.lagged[1],":", relev.var.names.lagged[2])), ":complem.ind", sep="")
                                                              , "score_diff_start", "drive_time_left_in_half", "drive_half_start"
                                                              , "score_diff_start:drive_time_left_in_half", "score_diff_start:drive_half_start", "drive_time_left_in_half:drive_half_start"
 ),
 collapse = " + "), collapse =" ")),
 data=pbp_by_drive.noNA[, c(if(incl.pos_team) c("pos_team", "def_pos_team", "pos.homefield", "complem.ind", 
                                                "score_diff_start", "drive_time_left_in_half", "drive_half_start") else NULL,
                            relev.var.names.lagged,
                            "score_pts")])
 
 
 
 cv.obj <- cv.glm(data = pbp_by_drive.noNA[, c(if(incl.pos_team) c(# "pos_team", "def_pos_team", 
                                                                   "pos.homefield", "complem.ind", 
                                                                   "score_diff_start", "drive_time_left_in_half", "drive_half_start") else NULL,
                                               relev.var.names.lagged,
                                               "score_pts")],
                  lm.only.complem.obj,
                  K=10,
                  cost=cost.fun)
 
 CV.results.only.complem <- rbind(CV.results.only.complem,
                                  data.frame(Year = year,
                                             RMSE = cv.obj$delta[1],
                                             SE = sqrt(cv.obj$delta[2]/nrow(pbp_by_drive.noNA)))
                                  )
 
 
 
  
}


print(CV.results.with.complem)
print(CV.results.no.complem)
print(CV.results.nothing)
print(CV.results.only.complem)


save(CV.results.with.complem, file = "LINEAR_NFL_W_START_POS_INTERACTION_CV.results.with.complem.Robj")
save(CV.results.no.complem, file = "LINEAR_NFL_W_START_POS_INTERACTION_CV.results.no.complem.Robj")
save(CV.results.nothing, file = "LINEAR_NFL_W_START_POS_INTERACTION_CV.results.nothing.Robj")
save(CV.results.only.complem, file = "LINEAR_NFL_W_START_POS_INTERACTION_CV.results.only.complem.Robj")

# load("LINEAR_NFL_W_START_POS_INTERACTION_CV.results.with.complem.Robj")
# load("LINEAR_NFL_W_START_POS_INTERACTION_CV.results.no.complem.Robj")
# load("LINEAR_NFL_W_START_POS_INTERACTION_CV.results.nothing.Robj")
# load("LINEAR_NFL_W_START_POS_INTERACTION_CV.results.only.complem.Robj")

print(mean(CV.results.with.complem$RMSE))
print(sd(CV.results.with.complem$RMSE)/sqrt(length(CV.results.with.complem$RMSE)))

print(mean(CV.results.no.complem$RMSE))
print(sd(CV.results.no.complem$RMSE)/sqrt(length(CV.results.no.complem$RMSE)))

print(mean(CV.results.nothing$RMSE))
print(sd(CV.results.nothing$RMSE)/sqrt(length(CV.results.nothing$RMSE)))

print(mean(CV.results.only.complem$RMSE))
print(sd(CV.results.only.complem$RMSE)/sqrt(length(CV.results.only.complem$RMSE)))



######
## RMSE
######

# > print(mean(CV.results.with.complem$RMSE))
# [1] 2.858955
# > print(sd(CV.results.with.complem$RMSE)/sqrt(length(CV.results.with.complem$RMSE)))
# [1] 0.00839838
# > 
#   > print(mean(CV.results.no.complem$RMSE))
# [1] 2.890138
# > print(sd(CV.results.no.complem$RMSE)/sqrt(length(CV.results.no.complem$RMSE)))
# [1] 0.007545691
# > 
#   > print(mean(CV.results.nothing$RMSE))
# [1] 2.899307
# > print(sd(CV.results.nothing$RMSE)/sqrt(length(CV.results.nothing$RMSE)))
# [1] 0.007875518
# > 
#   > print(mean(CV.results.only.complem$RMSE))
# [1] 2.871523
# > print(sd(CV.results.only.complem$RMSE)/sqrt(length(CV.results.only.complem$RMSE)))
# [1] 0.008375716


######
### MAE
######

# > print(mean(CV.results.with.complem$RMSE))
# [1] 2.332688
# > print(sd(CV.results.with.complem$RMSE)/sqrt(length(CV.results.with.complem$RMSE)))
# [1] 0.01254499
# > print(mean(CV.results.no.complem$RMSE))
# [1] 2.356263
# > print(sd(CV.results.no.complem$RMSE)/sqrt(length(CV.results.no.complem$RMSE)))
# [1] 0.01171096
# > 
#   > print(mean(CV.results.nothing$RMSE))
# [1] 2.399741
# > print(sd(CV.results.nothing$RMSE)/sqrt(length(CV.results.nothing$RMSE)))
# [1] 0.01223625
# > 
#   > print(mean(CV.results.only.complem$RMSE))
# [1] 2.379972
# > print(sd(CV.results.only.complem$RMSE)/sqrt(length(CV.results.only.complem$RMSE)))
# [1] 0.01265936